export const REGISTRATION_REQUEST_SENT = 'REGISTRATION_REQUEST_SENT';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_RESET_STATE = 'REGISTRATION_RESET_STATE';
